"""initial schema

Revision ID: a9583a2c2007
Revises: 
Create Date: 2026-09-11 20:07:10.235417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9583a2c2007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_seeds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('discovered_by', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Float(), nullable=False),
    sa.Column('same_domain_only', sa.Boolean(), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('pages_indexed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_seeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_seeds_domain'), ['domain'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('curriculum_tag', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)

    op.create_table('sandbox_audit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('dataset_id', sa.String(length=32), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('peak_memory_kb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('access_status', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('predatory_flag', sa.Boolean(), nullable=False),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seed_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seed_id'], ['crawl_seeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_pages_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_pages_seed_id'), ['seed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_pages_url'), ['url'], unique=False)

    op.create_table('source_chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('trust_tier', sa.String(length=16), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('allow_source_crawl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvases_project_id'), ['project_id'], unique=False)

    op.create_table('citations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=False),
    sa.Column('flagged_predatory', sa.Boolean(), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_profile', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memory_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memory_project_id'), ['project_id'], unique=False)

    op.create_table('threads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_thread_id', sa.String(length=32), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_project_id'), ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content_sw', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=8), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('dataset_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('output_files', sa.JSON(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Search and hot-path indexes are part of the schema contract. Keeping them
    # in migrations prevents a failed best-effort startup statement from leaving
    # production silently functional but pathologically slow.
    op.create_index('messages_thread_created_idx', 'messages', ['thread_id', 'created_at'])
    op.create_index('messages_project_created_idx', 'messages', ['project_id', 'created_at'])
    op.create_index('threads_project_updated_idx', 'threads', ['project_id', 'updated_at'])

    if bind.dialect.name == 'postgresql':
        op.execute(
            "ALTER TABLE source_chunks ADD COLUMN content_ts tsvector "
            "GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED"
        )
        op.execute(
            'CREATE INDEX source_chunk_ts_idx ON source_chunks USING GIN (content_ts)'
        )
    elif bind.dialect.name == 'sqlite':
        op.execute(
            "CREATE VIRTUAL TABLE IF NOT EXISTS source_chunk_fts "
            "USING fts5(chunk_id UNINDEXED, content, tokenize='unicode61')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        op.execute('DROP TABLE IF EXISTS source_chunk_fts')
    op.drop_index('threads_project_updated_idx', table_name='threads')
    op.drop_index('messages_project_created_idx', table_name='messages')
    op.drop_index('messages_thread_created_idx', table_name='messages')
    op.drop_table('analysis_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))

    op.drop_table('messages')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_project_id'))

    op.drop_table('threads')
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memory_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_memory_key'))

    op.drop_table('project_memory')
    op.drop_table('datasets')
    op.drop_table('citations')
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvases_project_id'))

    op.drop_table('canvases')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('source_chunks')
    with op.batch_alter_table('crawl_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_pages_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_pages_seed_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_pages_content_hash'))

    op.drop_table('crawl_pages')
    op.drop_table('sources')
    op.drop_table('sandbox_audit')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))

    op.drop_table('otp_codes')
    op.drop_table('institutions')
    with op.batch_alter_table('crawl_seeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_seeds_domain'))

    op.drop_table('crawl_seeds')
    # ### end Alembic commands ###
